name: user_market
description: E-commerce application
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.9.3
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_storage: ^11.2.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  google_sign_in: ^6.1.5  
  intl: ^0.18.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  skeletonizer: ^0.8.0
  synchronized: ^3.1.0
  uuid: ^4.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:      
      - assets/img/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400 
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600